In [1]:
# import the libraries


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# import the dataset

In [4]:
dataset = pd.read_csv(r'C:\Users\laptop\Desktop\Projects\- Predicting House Prices\Pune house data.csv')

In [5]:
dataset.head()

area_type   availability       size  society total_sqft  bath  \
0  Super built-up  Area         19-Dec      2 BHK  Coomee        1056   2.0   
1            Plot  Area  Ready To Move  4 Bedroom  Theanmp       2600   5.0   
2        Built-up  Area  Ready To Move      3 BHK      NaN       1440   2.0   
3  Super built-up  Area  Ready To Move      3 BHK  Soiewre       1521   3.0   
4  Super built-up  Area  Ready To Move      2 BHK      NaN       1200   2.0   

   balcony   price    site_location  
0      1.0   39.07      Alandi Road  
1      3.0  120.00  Ambegaon Budruk  
2      3.0   62.00       Anandnagar  
3      1.0   95.00            Aundh  
4      1.0   51.00       Aundh Road

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   area_type      13320 non-null  object 
 1   availability   13320 non-null  object 
 2   size           13304 non-null  object 
 3   society        7818 non-null   object 
 4   total_sqft     13320 non-null  object 
 5   bath           13247 non-null  float64
 6   balcony        12711 non-null  float64
 7   price          13320 non-null  float64
 8   site_location  13319 non-null  object 
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


In [7]:
dataset.shape

(13320, 9)

In [8]:
dataset.isnull().sum()

area_type           0
availability        0
size               16
society          5502
total_sqft          0
bath               73
balcony           609
price               0
site_location       1
dtype: int64

In [9]:
# We need to simple linear regression model to predict house prices based on features like
# the number of bedrooms and square footage so we need only three columns size , total_sqft , price


In [10]:
df = dataset[['size','total_sqft','price']].copy()

In [11]:
df

size total_sqft   price
0          2 BHK       1056   39.07
1      4 Bedroom       2600  120.00
2          3 BHK       1440   62.00
3          3 BHK       1521   95.00
4          2 BHK       1200   51.00
...          ...        ...     ...
13315  5 Bedroom       3453  231.00
13316      4 BHK       3600  400.00
13317      2 BHK       1141   60.00
13318      4 BHK       4689  488.00
13319      1 BHK        550   17.00

[13320 rows x 3 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   size        13304 non-null  object 
 1   total_sqft  13320 non-null  object 
 2   price       13320 non-null  float64
dtypes: float64(1), object(2)
memory usage: 312.3+ KB


In [13]:
df['size'].isnull().sum()

16

In [14]:
# Here size column consists some null values, we need to remove the null values

In [15]:
df.dropna(inplace = True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13304 entries, 0 to 13319
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   size        13304 non-null  object 
 1   total_sqft  13304 non-null  object 
 2   price       13304 non-null  float64
dtypes: float64(1), object(2)
memory usage: 415.8+ KB


In [17]:
df.head()

size total_sqft   price
0      2 BHK       1056   39.07
1  4 Bedroom       2600  120.00
2      3 BHK       1440   62.00
3      3 BHK       1521   95.00
4      2 BHK       1200   51.00

In [18]:
# rename the columns

In [19]:
df.rename(columns={"size":"Bedrooms","total_sqft":"Square_foot","price":"Price"},inplace=True)

In [20]:
df

Bedrooms Square_foot   Price
0          2 BHK        1056   39.07
1      4 Bedroom        2600  120.00
2          3 BHK        1440   62.00
3          3 BHK        1521   95.00
4          2 BHK        1200   51.00
...          ...         ...     ...
13315  5 Bedroom        3453  231.00
13316      4 BHK        3600  400.00
13317      2 BHK        1141   60.00
13318      4 BHK        4689  488.00
13319      1 BHK         550   17.00

[13304 rows x 3 columns]

In [21]:
df

Bedrooms Square_foot   Price
0          2 BHK        1056   39.07
1      4 Bedroom        2600  120.00
2          3 BHK        1440   62.00
3          3 BHK        1521   95.00
4          2 BHK        1200   51.00
...          ...         ...     ...
13315  5 Bedroom        3453  231.00
13316      4 BHK        3600  400.00
13317      2 BHK        1141   60.00
13318      4 BHK        4689  488.00
13319      1 BHK         550   17.00

[13304 rows x 3 columns]

In [22]:
df['Bedrooms'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [23]:
# We need only number of Bedrooms and its type of object we need to convert it to int

In [24]:
df['Bedrooms'] = df['Bedrooms'].str.split().str.get(0)

In [25]:
df['Bedrooms'] = df['Bedrooms'].astype(int)

In [26]:
df['Square_foot'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [27]:
df['Square_foot'] = df['Square_foot'].str.split().str.get(0)

In [28]:
 df['Square_foot'].unique()

array(['1056', '2600', '1440', ..., '2758', '774', '4689'], dtype=object)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13304 entries, 0 to 13319
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Bedrooms     13304 non-null  int32  
 1   Square_foot  13304 non-null  object 
 2   Price        13304 non-null  float64
dtypes: float64(1), int32(1), object(1)
memory usage: 363.8+ KB


In [30]:
df = df[df['Square_foot'].str.isnumeric()]

In [31]:
df

Bedrooms Square_foot   Price
0             2        1056   39.07
1             4        2600  120.00
2             3        1440   62.00
3             3        1521   95.00
4             2        1200   51.00
...         ...         ...     ...
13315         5        3453  231.00
13316         4        3600  400.00
13317         2        1141   60.00
13318         4        4689  488.00
13319         1         550   17.00

[13166 rows x 3 columns]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13166 entries, 0 to 13319
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Bedrooms     13166 non-null  int32  
 1   Square_foot  13166 non-null  object 
 2   Price        13166 non-null  float64
dtypes: float64(1), int32(1), object(1)
memory usage: 360.0+ KB


In [33]:
df['Square_foot'] = df['Square_foot'].astype(int)

C:\Users\laptop\AppData\Local\Temp\ipykernel_9060\715664509.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Square_foot'] = df['Square_foot'].astype(int)


In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13166 entries, 0 to 13319
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Bedrooms     13166 non-null  int32  
 1   Square_foot  13166 non-null  int32  
 2   Price        13166 non-null  float64
dtypes: float64(1), int32(2)
memory usage: 308.6 KB


In [35]:
df['Price'].unique()

array([ 39.07, 120.  ,  62.  , ...,  40.14, 231.  , 488.  ])

In [36]:
df['Price'] = df['Price'].astype(int)

C:\Users\laptop\AppData\Local\Temp\ipykernel_9060\1817184942.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = df['Price'].astype(int)


In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13166 entries, 0 to 13319
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Bedrooms     13166 non-null  int32
 1   Square_foot  13166 non-null  int32
 2   Price        13166 non-null  int32
dtypes: int32(3)
memory usage: 257.1 KB


In [39]:
# splitting into dependent and independent variable

In [56]:
X = df[['Bedrooms','Square_foot']].values
y = df[['Price']].values

In [57]:
X

array([[   2, 1056],
       [   4, 2600],
       [   3, 1440],
       ...,
       [   2, 1141],
       [   4, 4689],
       [   1,  550]])

In [58]:
y

array([[ 39],
       [120],
       [ 62],
       ...,
       [ 60],
       [488],
       [ 17]])

In [59]:
# splitting data into training and test set

In [60]:
from sklearn.model_selection import train_test_split

In [135]:
X_train,X_test,y_train,y_test = train_test_split( X , y ,test_size =0.1,random_state=354)

In [136]:
X_train

array([[   2, 1080],
       [   3, 1210],
       [   3, 1305],
       ...,
       [   4, 2403],
       [   3, 1650],
       [   2, 1200]])

In [137]:
y_train

array([[ 43],
       [ 57],
       [ 58],
       ...,
       [270],
       [ 78],
       [150]])

In [138]:
from sklearn.linear_model import LinearRegression

In [139]:
regressor = LinearRegression()

In [140]:
regressor.fit(X_train,y_train)

LinearRegression()

In [141]:
y_pred = regressor.predict(X_test)

In [142]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6478164755723448

In [ ]:
# 